export enum IdentityErrorCodes {
    USERNAME_NOT_FOUND = 'USER_NOT_FOUND',
    PASSWORD_IS_WRONG = 'WRONG_PASSWORD',
    TOKEN_IS_EXPIRED = 'TOKEN_EXPIRED',
    TOKEN_IS_NOT_VALID = 'INVALID_TOKEN',
}