export enum ErrorCodes {
    TRANSACTION_PROCESSED = 'TRANSACTION_ALREADY_PROCESSED',
    PAYMENT_FAILURE = 'PAYMENT_FAILURE',
    DATABASE_SAVE_ERROR = 'DATABASE_SAVING_FAILURE',
    INVALID_PLAN_ID = 'INVALID_PLAN_ID',
    USER_NOT_FOUND = 'USER_NOT_FOUND',
    TRANSACTION_KEY_NOT_FOUND = 'TRANSACTION_KEY_NOT_FOUND'
}